name = input()
surname = input()
animal = input()
Zodiac = input()
print(f"Индивидуальный гороскоп для пользователя {name} {surname}. Кем вы были в прошлой жизни: {animal}. Ваш знак зодиака - Zodiac , поэтому вы - тонко чувствующая натура.")
